### PR TITLE
Update profiles 'junction-' and 'dolomite-devel-'

### PR DESCRIPTION
**Pull request by StuartWheater**
Updates to latest Rock and R.

### CODE REVIEW

**Review by ymarcon — CHANGES_REQUESTED** [review]
See also what I just done with the rock-base image: I have moved the base folder to the branch "base", and thanks to github actions when I make a release of this branch, the image is automatically built and pushed to the corresponding docker hub repo, with a build attestation. We should consider using this pattern for all the rock-base flavors, it is clean (image build environment is controlled) and secure (build tracking).

**Comment by ymarcon** [comment]
See the action that built the datashield/rock-base image:
https://github.com/datashield/docker-rock/actions/runs/9094991337

**Review by ymarcon — APPROVED** [review]
Approved but I think we need to discuss about automating the builds.

**Comment by StuartWheater** [comment]
Agreed

**Pull request merged**
